name: blinking_timer
description: A customizable countdown timer with blinking effects that intensify as time runs out.
version: 1.0.0
homepage: https://github.com/yourusername/blinking_timer
repository: https://github.com/yourusername/blinking_timer

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
