name: blinking_timer
description: A customizable countdown timer with blinking effects that intensify as time runs out.
version: 1.0.2
license: BSD-3-Clause
repository: https://github.com/dev-zeb/blinking_timer
documentation: https://github.com/dev-zeb/blinking_timer#readme
issue_tracker: https://github.com/dev-zeb/blinking_timer/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
